name: "Helm Action"
description: "Custom action to manage Helm commands"
inputs:
  command:
    description: "The Helm command to run"
    required: true
  atomic_timeout:
    description: "Timeout for Helm atomic command"
    required: false
    default: "3m"
  repository_name:
    description: "Path to the Helm chart"
    required: true
  chart_directory:
    description: "The name of the chart directory"
    required: true
  environment:
    description: "Environment for the Helm release"
    required: false    
  release_name:
    description: "Helm release name"
    required: false    
  namespace:
    description: "Namespace for the Helm release"
    required: false  
  image_tag:
    description: "Docker image tag for the Helm release"
    required: false
  dry_run:
    description: "Whether to run the command in dry-run mode"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - run: |
        chmod +x ${{ github.action_path }}/main.sh
        ${{ github.action_path }}/main.sh "${{ inputs.command }}" "${{ inputs.atomic_timeout }}" "${{ inputs.repository_name }}" "${{ inputs.chart_directory }}" "${{ inputs.environment }}" "${{ inputs.release_name }}" "${{ inputs.namespace }}" "${{ inputs.image_tag }}" "${{ inputs.dry_run }}" 
      shell: bash
