name: 'Slack Notification Action'
description: 'Send a notification to Slack'
inputs:
  slack-webhook-url:
    description: 'Slack Webhook URL'
    required: true
  github-job:
    description: 'GitHub Job'
    required: true
  github-actor:
    description: 'GitHub Actor'
    required: true
  git-sha:
    description: 'Git Commit SHA'
    required: true
  repository-name:
    description: 'Repository Name'
    required: true
  environment:
    description: 'Environment'
    required: true
  status:
    description: 'Status (started, success, failure)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Notify Slack
      run: |
        if [ "${{ inputs.status }}" == "STARTED" ]; then
          COLOR="ffc500"
        elif [ "${{ inputs.status }}" == "SUCCESS" ]; then
          COLOR="09db09"
        elif [ "${{ inputs.status }}" == "FAILED" ]; then
          COLOR="ff0006"
        else
          COLOR="439FE0"
        fi

        TIMESTAMP=$(date +%FT%T%Z)
        EVENT_NAME=${{ github.event_name }}
        if [ "$EVENT_NAME" == "pull_request" ]; then
          PR_URL=${{ github.event.pull_request.html_url }}
          PR_TEXT="Pull Request URL: <$PR_URL|${PR_URL}>"
        else
          PR_TEXT=""
        fi

        COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ inputs.git-sha }}"
        ACTION_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      
        curl ${{ inputs.slack-webhook-url }} \
          --request POST \
          --header 'Content-Type: application/json' \
          --data \
            '{
              "attachments": [{
                    "color": "'"$COLOR"'",
                    "blocks": [
                      {
                        "type": "header",
                        "text": {
                          "type": "plain_text",
                          "text": "'"${{ inputs.status }}"': Job '${{ inputs.github-job }}'"
                       }
                     },
                     {
                        "type": "section",
                       "fields": [
                         {
                            "type": "mrkdwn",
                            "text": "*Triggered by:*\n<https://github.com/${{ github.repository }}/commit/${{ inputs.git-sha }}|$GITHUB_ACTOR>"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Git Commit ID:*\n<${COMMIT_URL}|${{ inputs.git-sha }}>"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Application:*\n${{ inputs.repository-name }}"
                         },
                          {
                            "type": "mrkdwn",
                            "text": "*Environment:*\n${{ inputs.environment }}"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Event:*\n${EVENT_NAME}"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "${PR_TEXT}"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Action URL:*\n<${ACTION_URL}|View Action>"
                          },
                          {
                            "type": "mrkdwn",
                            "text": ":clock3: *Timestamp:*\n<!date^$TIMESTAMP^{date_pretty} at {time_secs}|Date not available>"
                          }
                        ],
                        "accessory": {
                          "type": "image",
                          "image_url": "https://avatars.githubusercontent.com/${{ inputs.github-actor }}?s=48",
                          "alt_text": "avatar"
                        }
                      }
                    ]
                 }]
            }'
      shell: bash
